<?php

namespace Drupal\club_test;

class ListMaxID {

	/**
	 * Generate SQL code to set auto_increment value on server after
	 *  database import failed to complete and ALTER statements left this unset.
	 */
	public static function getMax() {

    $output = "";
    $tables = [
      ['block_content_revision', 'revision_id'],
      ['block_content', 'id'],
      ['civicrm_acl_cache', 'id'],
      ['civicrm_acl_contact_cache', 'id'],
      ['civicrm_acl_entity_role', 'id'],
      ['civicrm_acl', 'id'],
      ['civicrm_action_log', 'id'],
      ['civicrm_action_schedule', 'id'],
      ['civicrm_activity_contact', 'id'],
      ['civicrm_activity', 'id'],
      ['civicrm_address_format', 'id'],
      ['civicrm_address', 'id'],
      ['civicrm_afform_submission', 'id'],
      ['civicrm_batch', 'id'],
      ['civicrm_cache', 'id'],
      ['civicrm_campaign_group', 'id'],
      ['civicrm_campaign', 'id'],
      ['civicrm_case_activity', 'id'],
      ['civicrm_case_contact', 'id'],
      ['civicrm_case_type', 'id'],
      ['civicrm_case', 'id'],
      ['civicrm_component', 'id'],
      ['civicrm_contact_type', 'id'],
      ['civicrm_contact', 'id'],
      ['civicrm_contribution_page', 'id'],
      ['civicrm_contribution_product', 'id'],
      ['civicrm_contribution_recur', 'id'],
      ['civicrm_contribution_soft', 'id'],
      ['civicrm_contribution_widget', 'id'],
      ['civicrm_contribution', 'id'],
      ['civicrm_country', 'id'],
      ['civicrm_county', 'id'],
      ['civicrm_currency', 'id'],
      ['civicrm_custom_field', 'id'],
      ['civicrm_custom_group', 'id'],
      ['civicrm_cxn', 'id'],
      ['civicrm_dashboard_contact', 'id'],
      ['civicrm_dashboard', 'id'],
      ['civicrm_dedupe_exception', 'id'],
      ['civicrm_dedupe_rule_group', 'id'],
      ['civicrm_dedupe_rule', 'id'],
      ['civicrm_discount', 'id'],
      ['civicrm_domain', 'id'],
      ['civicrm_email', 'id'],
      ['civicrm_entity_batch', 'id'],
      ['civicrm_entity_file', 'id'],
      ['civicrm_entity_financial_account', 'id'],
      ['civicrm_entity_financial_trxn', 'id'],
      ['civicrm_entity_tag', 'id'],
      ['civicrm_event_carts', 'id'],
      ['civicrm_event', 'id'],
      ['civicrm_events_in_carts', 'id'],
      ['civicrm_extension', 'id'],
      ['civicrm_file', 'id'],
      ['civicrm_financial_account', 'id'],
      ['civicrm_financial_item', 'id'],
      ['civicrm_financial_trxn', 'id'],
      ['civicrm_financial_type', 'id'],
      ['civicrm_group_contact_cache', 'id'],
      ['civicrm_group_contact', 'id'],
      ['civicrm_group_nesting', 'id'],
      ['civicrm_group_organization', 'id'],
      ['civicrm_group', 'id'],
      ['civicrm_im', 'id'],
      ['civicrm_job_log', 'id'],
      ['civicrm_job', 'id'],
      ['civicrm_line_item', 'id'],
      ['civicrm_loc_block', 'id'],
      ['civicrm_location_type', 'id'],
      ['civicrm_log', 'id'],
      ['civicrm_mail_settings', 'id'],
      ['civicrm_mailing_abtest', 'id'],
      ['civicrm_mailing_bounce_pattern', 'id'],
      ['civicrm_mailing_bounce_type', 'id'],
      ['civicrm_mailing_component', 'id'],
      ['civicrm_mailing_event_bounce', 'id'],
      ['civicrm_mailing_event_confirm', 'id'],
      ['civicrm_mailing_event_delivered', 'id'],
      ['civicrm_mailing_event_forward', 'id'],
      ['civicrm_mailing_event_opened', 'id'],
      ['civicrm_mailing_event_queue', 'id'],
      ['civicrm_mailing_event_reply', 'id'],
      ['civicrm_mailing_event_subscribe', 'id'],
      ['civicrm_mailing_event_trackable_url_open', 'id'],
      ['civicrm_mailing_event_unsubscribe', 'id'],
      ['civicrm_mailing_group', 'id'],
      ['civicrm_mailing_job', 'id'],
      ['civicrm_mailing_recipients', 'id'],
      ['civicrm_mailing_spool', 'id'],
      ['civicrm_mailing_trackable_url', 'id'],
      ['civicrm_mailing', 'id'],
      ['civicrm_managed', 'id'],
      ['civicrm_mapping_field', 'id'],
      ['civicrm_mapping', 'id'],
      ['civicrm_membership_block', 'id'],
      ['civicrm_membership_log', 'id'],
      ['civicrm_membership_payment', 'id'],
      ['civicrm_membership_status', 'id'],
      ['civicrm_membership_type', 'id'],
      ['civicrm_membership', 'id'],
      ['civicrm_menu', 'id'],
      ['civicrm_mosaico_msg_template', 'id'],
      ['civicrm_mosaico_template', 'id'],
      ['civicrm_msg_template', 'id'],
      ['civicrm_navigation', 'id'],
      ['civicrm_note', 'id'],
      ['civicrm_openid', 'id'],
      ['civicrm_option_group', 'id'],
      ['civicrm_option_value', 'id'],
      ['civicrm_participant_payment', 'id'],
      ['civicrm_participant_status_type', 'id'],
      ['civicrm_participant', 'id'],
      ['civicrm_payment_processor_type', 'id'],
      ['civicrm_payment_processor', 'id'],
      ['civicrm_payment_token', 'id'],
      ['civicrm_pcp_block', 'id'],
      ['civicrm_pcp', 'id'],
      ['civicrm_phone', 'id'],
      ['civicrm_pledge_block', 'id'],
      ['civicrm_pledge_payment', 'id'],
      ['civicrm_pledge', 'id'],
      ['civicrm_preferences_date', 'id'],
      ['civicrm_premiums_product', 'id'],
      ['civicrm_premiums', 'id'],
      ['civicrm_prevnext_cache', 'id'],
      ['civicrm_price_field_value', 'id'],
      ['civicrm_price_field', 'id'],
      ['civicrm_price_set_entity', 'id'],
      ['civicrm_price_set', 'id'],
      ['civicrm_print_label', 'id'],
      ['civicrm_product', 'id'],
      ['civicrm_queue_item', 'id'],
      ['civicrm_queue', 'id'],
      ['civicrm_recurring_entity', 'id'],
      ['civicrm_relationship_cache', 'id'],
      ['civicrm_relationship_type', 'id'],
      ['civicrm_relationship', 'id'],
      ['civicrm_report_instance', 'id'],
      ['civicrm_saved_search', 'id'],
      ['civicrm_search_display', 'id'],
      ['civicrm_search_segment', 'id'],
      ['civicrm_setting', 'id'],
      ['civicrm_sms_provider', 'id'],
      ['civicrm_state_province', 'id'],
      ['civicrm_status_pref', 'id'],
      ['civicrm_subscription_history', 'id'],
      ['civicrm_survey', 'id'],
      ['civicrm_system_log', 'id'],
      ['civicrm_tag', 'id'],
      ['civicrm_tell_friend', 'id'],
      ['civicrm_timezone', 'id'],
      ['civicrm_translation', 'id'],
      ['civicrm_uf_field', 'id'],
      ['civicrm_uf_group', 'id'],
      ['civicrm_uf_join', 'id'],
      ['civicrm_uf_match', 'id'],
      ['civicrm_user_job', 'id'],
      ['civicrm_value_contacts_6', 'id'],
      ['civicrm_value_emergency_con_1', 'id'],
      ['civicrm_value_member_waiver_4', 'id'],
      ['civicrm_value_participant_w_5', 'id'],
      ['civicrm_website', 'id'],
      ['civicrm_word_replacement', 'id'],
      ['civicrm_worldregion', 'id'],
      ['club_contacts', 'contact_id'],
      ['club_paypal', 'id'],
      ['club_schedule', 'schedule_id'],
      ['comment', 'cid'],
      ['contact_message', 'id'],
      ['content_moderation_state_revision', 'revision_id'],
      ['content_moderation_state', 'id'],
      ['crop_revision', 'vid'],
      ['crop', 'cid'],
      ['file_managed', 'fid'],
      ['flood', 'fid'],
      ['honeypot_user', 'id'],
      ['media_revision', 'vid'],
      ['media', 'mid'],
      ['menu_link_content_revision', 'revision_id'],
      ['menu_link_content', 'id'],
      ['menu_tree', 'mlid'],
      ['node_revision', 'vid'],
      ['node', 'nid'],
      ['paragraphs_item_revision', 'revision_id'],
      ['paragraphs_item', 'id'],
      ['path_alias_revision', 'revision_id'],
      ['path_alias', 'id'],
      ['queue', 'item_id'],
      ['sequences', 'value'],
      ['shortcut', 'id'],
      ['smart_date_override', 'id'],
      ['smart_date_rule', 'rid'],
      ['taxonomy_term_data', 'tid'],
      ['taxonomy_term_revision', 'revision_id'],
      ['users', 'uid'],
      ['watchdog', 'wid'],
      ['webform_submission', 'sid'],
    ];

    foreach ($tables as $table) {
      $max = \Drupal::database()
        ->query("SELECT MAX($table[1]) AS max FROM $table[0]")
        ->fetch();
      // PHP 8: calling reset on an object is deprecated, must call get_mangled_object_vars first.
      $max = get_mangled_object_vars($max);
      $max = reset($max);
      $next = $max + 1;

      //Format to put in excel, delimit columns with | and sort by max.
      $output .= "ALTER TABLE $table[0] AUTO_INCREMENT = $next;|$max<br>";
    }  
    echo $output; die;
	}
}
