<?php

use Drupal\Core\Datetime\DrupalDateTime;
use Drupal\datetime\Plugin\Field\FieldType\DateTimeItemInterface;

//use Drupal\user\Entity\Role;
use Drupal\node\Entity\Node;
use Drupal\user\Entity\User;
use Drupal\taxonomy\Entity\Term;
use Drupal\Core\Entity\EntityTypeManagerInterface;
use Drupal\Core\Entity\EntityStorageInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Theme\ThemeManagerInterface;
use Drupal\webform\Entity\WebformSubmission;
use Drupal\views\ViewExecutableFactory;
use Drupal\file_mdm\FileMetadataManagerInterface;

/*
 * Implement hook_help.
 * Test code is written to help page
 */
function club_test_help($route_name, RouteMatchInterface $route_match) {

  if ($route_name == 'help.page.club_test') {

    
 
  }
}
