_core:
  default_config_hash: ALrmD1SCpEpTvkP6L2jqsOPnHOGPciQIIu3lgtjGHtU
filter_format: plain_text
enabled_entity_types:
  - civicrm_activity
  - civicrm_contribution
  - civicrm_membership
  - civicrm_participant
disable_hooks: false
enable_links_per_type:
  civicrm_activity:
    values:
      view: view
      add: add
      edit: edit
      delete: delete
  civicrm_contribution:
    values:
      view: view
      add: add
      edit: edit
      delete: delete
  civicrm_membership:
    values:
      view: view
      add: add
      edit: edit
      delete: delete
  civicrm_participant:
    values:
      view: view
      add: add
      edit: edit
      delete: delete
disable_links: false
disable_hooks_per_type:
  civicrm_activity: 0
  civicrm_address: 0
  civicrm_campaign: 0
  civicrm_case: 0
  civicrm_case_type: 0
  civicrm_contact: 0
  civicrm_contribution: 0
  civicrm_contribution_recur: 0
  civicrm_contribution_page: 0
  civicrm_country: 0
  civicrm_email: 0
  civicrm_entity_tag: 0
  civicrm_entity_financial_trxn: 0
  civicrm_financial_account: 0
  civicrm_financial_trxn: 0
  civicrm_financial_type: 0
  civicrm_event: 0
  civicrm_group: 0
  civicrm_group_contact: 0
  civicrm_im: 0
  civicrm_line_item: 0
  civicrm_loc_block: 0
  civicrm_membership: 0
  civicrm_membership_payment: 0
  civicrm_membership_type: 0
  civicrm_note: 0
  civicrm_participant: 0
  civicrm_participant_status_type: 0
  civicrm_participant_payment: 0
  civicrm_payment_processor: 0
  civicrm_payment_processor_type: 0
  civicrm_phone: 0
  civicrm_pledge: 0
  civicrm_pledge_payment: 0
  civicrm_price_set: 0
  civicrm_price_field: 0
  civicrm_price_field_value: 0
  civicrm_recurring_entity: 0
  civicrm_relationship: 0
  civicrm_relationship_type: 0
  civicrm_survey: 0
  civicrm_state_province: 0
  civicrm_tag: 0
  civicrm_custom_field: 0
  civicrm_custom_group: 0
  civicrm_website: 0
  civicrm_mailing: 0
  civicrm_mailing_job: 0
  civicrm_option_value: 0
  civicrm_contribution_soft: 0
  civicrm_pcp: 0
