<?php

use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\user\Entity\User;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Entity\EntityDefinitionUpdateManagerInterface;

/**
 * Implements hook_install().
 *
 * @see system_install()
 */
function club_ride_tools_install() {
  
  // Add permissions to roles. 
  $roles = [
    'anonymous' => [
      'view club_route entity',
    ],
    'authenticated' => [
      'view club_route entity',
    ],
    'ride_leader' => [
      'add club_route entity',
      'enter waivers',
      'view club_schedule entity',
    ],
    'rides_coordinator' => [
      'add club_route entity',
      'delete club_route entity',
      'edit club_route entity',
      'enter waivers',
      'edit club_schedule entity',
      'view club_schedule entity',
    ],
    'site_admin' => [
      'administer rwgps_api_form',
      'add club_route entity',
      'delete club_route entity',
      'edit club_route entity',
      'enter waivers',
      'edit club_schedule entity',
      'view club_schedule entity',
    ],
    'membership' => ['enter waivers'],
  ];

  foreach ($roles as $role => $permissions) {
    $role = \Drupal\user\Entity\Role::load($role);

    if ($role) {
      foreach ($permissions as $permission) {
        $role->grantPermission($permission);
      }
      $role->save();
    }
  }

  drupal_flush_all_caches();
}

